AccountId:
  name: account_id
  in: path
  required: true
  schema:
    type: string
    format: uuid

EventId:
  name: event_id
  in: path
  required: true
  description: 24-character hex string (MongoDB ObjectId)
  schema:
    type: string
    pattern: "^[a-f0-9]{24}$"
