AccountId:
  name: id
  in: path
  required: true
  description: MetaTrader account ID
  schema:
    type: integer

EventId:
  name: event_id
  in: path
  required: true
  description: 24-character hex string (MongoDB ObjectId)
  schema:
    type: string
    pattern: "^[a-f0-9]{24}$"

ApiKeyId:
  name: id
  in: path
  required: true
  schema:
    type: string
    format: uuid

FileName:
  name: file_name
  in: path
  required: true
  description: Unique file name returned by the upload endpoint
  schema:
    type: string
