# Generated by Django 5.2.11 on 2026-02-26 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(default="application/octet-stream", max_length=255),
                ),
                ("size", models.BigIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="app.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_files",
            },
        ),
    ]
