# Generated by Django 5.2.5 on 2026-03-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
